# Basic Site Settings
locale        : "en-US"
site_theme    : "default"
title         : "Sophia DiPietro | Academic Website"
name          : &name "Sophia DiPietro"
description   : &description "Graduate researcher at UM/RSMAS studying extreme heat, humid heat, and ocean–land coupling."
url           : "https://sophiadipietro.github.io"   # change to https://sophiadipietro.com when DNS is ready
baseurl       : ""
repository    : "sophiadipietro/sophiadipietro.github.io"

# Author sidebar/profile
author:
  avatar      : "images/profile.png"   # add your headshot at /images/profile.png
  name        : "Sophia DiPietro"
  pronouns    : "she/her"
  bio         : "Graduate Research Assistant, RSMAS (UM). Extreme heat, humid heat, and ocean–land coupling."
  location    : "Miami, FL"
  email       : "YOUR_EMAIL@miami.edu"

  # Academic profiles
  googlescholar: "https://scholar.google.com/citations?user=YOUR_ID"
  orcid        : "https://orcid.org/YOUR-ORCID"

  # Social links
  github       : "sophiadipietro"
  linkedin     : "YOUR-LINKEDIN"
  twitter      : "YOUR-TWITTER"

# Navigation bar items
navigation:
  - title: "Home"
    url: /about/
  - title: "Timeline"
    url: /timeline/
  - title: "CV"
    url: /cv/

# Site Settings
timezone      : America/New_York
markdown      : kramdown
highlighter   : rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

