# Basic Site Settings
locale        : "en-US"
site_theme    : "default"
title         : "Sophia DiPietro | Academic Website"
name          : &name "Sophia DiPietro"
description   : &description "Graduate researcher at UM/RSMAES studying climate science, hazard mitigation, extreme events, and usable science."
url           : "https://sophiadipietro.github.io"   # change to https://sophiadipietro.com when DNS is ready
baseurl       : ""
repository    : "sophiadipietro/sophiadipietro.github.io"

# Author sidebar/profile
author:
  avatar      : "images/sophia_dipietro.jpeg"   # add your headshot at /images/profile.png
  name        : "Sophia DiPietro"
  pronouns    : "she/her"
  bio         : "Graduate Research Assistant, RSMAES (UM).  In 2024, I graduated from Barnard College of Columbia University with a degree in Environmental Science and Sustainability, and was a member of  Columbia-Barnard Women's Rowing team. My research interests include climate science, hazard mitigation, and extreme events. I enjoy working at the intersection of science and policy, and have experience with public outreach."
  location    : "Miami, FL"
  email       : "sophia.dipietro@earth.miami.edu"

  # Academic profiles
  googlescholar: "https://scholar.google.com/citations?user=7DwsirMAAAAJ&hl=en"
  orcid        : "https://orcid.org/0009-0004-8143-7075"

  # Social links
  github       : "sophiadipietro"
  linkedin     : "https://www.linkedin.com/in/sophia-d-6565261bb/"
  bluesky      : "https://bsky.app/profile/sophiadipietro.bsky.social"

# Navigation bar items
navigation:
  - title: "Home"
    url: /about/
  - title: "Timeline"
    url: /timeline/
  - title: "CV"
    url: /cv/

# Site Settings
timezone      : America/New_York
markdown      : kramdown
highlighter   : rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

