# Basic Site Settings
locale        : "en-US"
site_theme    : "default"
title         : "Sophia DiPietro | PhD Student @UM"
name          : &name "Sophia DiPietro"
description   : &description "PhD Student at UM/RSMAES studying climate science, hazard mitigation, extreme events, and usable science."
url           : "https://sophiadipietro.com"   # change to https://sophiadipietro.com when DNS is ready
baseurl       : ""
repository    : "sophiadipietro/sophiadipietro.github.io"

# Author sidebar/profile
author:
  name        : "Sophia DiPietro"
  pronouns    : "she/her"
  bio         : "PhD Student, RSMAES (UM). I am a PhD student in the Atmospheric Science Department, focusing on extreme events and climate change."
  location    : "Miami, FL"
  email       : "sophia.dipietro@earth.miami.edu"

  # Academic profiles
  googlescholar: "https://scholar.google.com/citations?user=7DwsirMAAAAJ&hl=en"
  orcid        : "https://orcid.org/0009-0004-8143-7075"

  # Social links
  github       : "sdipietro2002"
  linkedin     : "www.linkedin.com/in/sophia-d-6565261bb"
  bluesky      : "https://bsky.app/profile/sophiadipietro.bsky.social"

# Navigation bar items
navigation:
  - title: "Home"
    url: /about/
  - title: "Timeline"
    url: /timeline/
  - title: "CV"
    url: /cv/
include:
  - _pages
  - files
timezone      : America/New_York
markdown      : kramdown
highlighter   : rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

